simple_twitter_client/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('web_site.urls', namespace='web_site')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
]

web_site/urls.py
# coding: utf-8
from django.conf.urls import url

from web_site import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^followers$', views.FollowerListView.as_view(), name="followers"),
    url(r'^followers/(?P<pk>[0-9]+)$', views.FollowerDetailView.as_view(), name="follower"),
    url(r'^remove$', views.RemoveAccountView.as_view(), name="remove"),
]

web_site/models.py
# coding: utf-8
from __future__ import unicode_literals

import tweepy
from allauth.account.signals import user_signed_up
from allauth.socialaccount.models import SocialApp
from django.conf import settings
from django.db import models
from django.urls import reverse


# One twitter account can follow two ore more users.
# So, better way is to make many-to-many relationship between Follower model and AUTH_USER_MODEL
class Follower(models.Model):
    """ User's twitter followers list """

    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    twitter_id = models.BigIntegerField(verbose_name='Twitter account id')
    screen_name = models.CharField(max_length=128, db_index=True)
    name = models.CharField(max_length=128)
    description = models.TextField(blank=True)
    followers_count = models.IntegerField(verbose_name='Number of followers', default=0)
    lang = models.CharField(max_length=3, verbose_name="Follower's language")
    image_url = models.URLField(blank=True, max_length=300, verbose_name="Follower's profile image URL")

    @property
    def full_screen_name(self):
        return "@{0}".format(self.screen_name)

    def get_absolute_url(self):
        return reverse("web_site:follower", kwargs={'pk': self.pk})

    def __unicode__(self):
        return self.full_screen_name


# better approach is synchronization followers asynchronously. I will reduce time user waiting after registration.
# Extra http requests to Twitter take time and suffer from possible network connection problems
# Run async task just after registration and run it periodically to load new followers
def sync_followers(request, user, **kwargs):
    """ Sync user's followers after sign up """

    social_login = kwargs['sociallogin']
    consumer_key = social_login.token.app.client_id
    consumer_secret = social_login.token.app.secret
    access_token = social_login.token.token
    access_token_secret = social_login.token.token_secret

    auth_handler = tweepy.OAuthHandler(consumer_key, consumer_secret)
    auth_handler.set_access_token(access_token, access_token_secret)
    twitter_api = tweepy.API(auth_handler)

    followers = []
    for follower in tweepy.Cursor(twitter_api.followers).items():
        followers.append(
            Follower(user=user, twitter_id=follower.id, screen_name=follower.screen_name, name=follower.name,
                     description=follower.description, image_url=follower.profile_image_url,
                     followers_count=follower.followers_count, lang=follower.lang,
                     )
        )
    Follower.objects.bulk_create(followers, batch_size=100)


user_signed_up.connect(sync_followers)

web_site/views.py
# coding: utf-8
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic

from web_site import models


class IndexView(generic.TemplateView):
    template_name = "web_site/index.html"

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['after_login_url'] = reverse("web_site:followers")
        return context


class FollowerListView(LoginRequiredMixin, generic.ListView):
    login_url = reverse_lazy('web_site:index')
    template_name = "web_site/followers.html"
    context_object_name = 'followers'

    def get_queryset(self):
        qs = models.Follower.objects.filter(user=self.request.user)
        q = self.request.GET.get('q', None)
        if q:
            return qs.filter(screen_name__icontains=q)
        return qs

    def get_context_data(self, **kwargs):
        cd = super(FollowerListView, self).get_context_data(**kwargs)
        cd['q'] = self.request.GET.get('q', '')
        return cd


class FollowerDetailView(LoginRequiredMixin, generic.DetailView):
    login_url = reverse_lazy('web_site:index')
    template_name = 'web_site/follower.html'
    context_object_name = 'follower'
    model = models.Follower


class RemoveAccountView(LoginRequiredMixin, generic.View):
    login_url = reverse_lazy('web_site:index')

    def post(self, *args, **kwargs):
        self.request.user.delete()
        return HttpResponseRedirect(reverse("web_site:index"))

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Simple twitter client for LifeTech</title>

    <link href="{% static "/css/bootstrap.min.css" %}" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

<div class="container">
    {% block content %}
    {% endblock %}
</div>

<script src="{% static '/js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/web_site/follower.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <h1>
            {% if follower.image_url %}
                <img src="{{ follower.image_url }}">
            {% endif %}
            {{ follower.full_screen_name }}
        </h1>

        <p>{{ follower.name }}</p>
        {% if follower.description %}
            <p>{{ follower.description }}</p>
        {% endif %}
        <p>Language: {{ follower.lang }}</p>

        <p>Number of followers: {{ follower.followers_count }}</p>

        <a href="{% url "web_site:followers" %}" class="btn btn-default">
            <i class="glyphicon glyphicon-arrow-left"></i>
            To list of followers
        </a>
    </div>
{% endblock %}

templates/web_site/followers.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-lg-6">
            <h1>@{{ user }} followers</h1>

            <form>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">@</span>
                    <input type="text" name="q" class="form-control" placeholder="Screen name" value="{{ q }}">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">Search</button>
                    </span>
                </div>
            </form>

            <a href="{% url "web_site:index" %}" class="btn btn-default" style="margin-top: 10px">
                <i class="glyphicon glyphicon-arrow-left"></i>
                To index page
            </a>
        </div>
    </div>
    <div class="row" style="margin-top: 25px">
        <div class="col-lg-12">
            {% if followers %}
                <ul class="media-list">
                    {% for follower in followers %}
                        <li class="media">
                            <div class="media-left">
                                <a href="{{ follower.get_absolute_url }}">
                                    <img class="media-object" src="{{ follower.image_url }}" alt="no photo">
                                </a>
                            </div>
                            <div class="media-body">
                                <a href="{{ follower.get_absolute_url }}">
                                    <h4 class="media-heading">{{ follower.full_screen_name }}</h4>
                                </a>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>Yo do not have any follower =/</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/web_site/index.html
{% extends "base.html" %}

{% load socialaccount %}

{% block content %}
    <div class="row">
        <div class="col-lg-12 text-center" style="margin-top: 40vh">
            {% if not user.is_anonymous %}
                <p>You are logged in as {{ user }}</p>

                <p>
                    <a href="{% url "web_site:followers" %}" class="btn btn-default">Go to list of followers</a>
                </p>

                <p>
                    <form method="POST" action="{% url "account_logout" %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-default">Log out</button>
                    </form>
                </p>

                <p>
                    <form method="POST" action="{% url "web_site:remove" %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger" title="Remove account and related followers">
                            Remove account
                        </button>
                    </form>
                </p>
            {% else %}
                <a href="{% provider_login_url "twitter" next=after_login_url %}" class="btn btn-default btn-lg">
                    Enter using Twitter
                </a>
            {% endif %}
        </div>
    </div>
{% endblock %}